---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitrepo-main
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/kingdonb/simplest-commitbee

