---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mark-app
spec:
  chart:
    spec:
      chart: charts/marxc
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: gitrepo-main
  interval: 1m0s
  releaseName: mark
