# ./.github/workflows/02-docker-build.yaml
name: Docker Build, Push

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'release/*'

jobs:
  docker:
    env:
      IMAGE: kingdonb/simplest-commitbee
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          ts=$(date +%s)
          VERSION=${GITHUB_SHA::8}
          BUILD_ID="${branch}-${VERSION}-${ts}"
          LATEST_ID=canary
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BUILD_ID=${GITHUB_REF/refs\/tags\//}
            LATEST_ID=latest
          fi
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_OUTPUT
          echo "LATEST_ID=${LATEST_ID}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE}}:${{ steps.prep.outputs.BUILD_ID }}
            ${{ env.IMAGE}}:${{ steps.prep.outputs.LATEST_ID }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
